version: "3.8"

services:
  app:
    build:
      context: .
      target: base
    image: aifrak/shell-utils:latest
    volumes:
      - .:/app
      - app-node-modules:/app/node_modules

volumes:
  app-node-modules:
