name: Markdown linter

on:
  push:
    paths:
      - '**.md'

jobs:
  linters:
    name: Markdown linter
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Markdown linter (markdownlint-cli)
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
