name: Tests

on:
  push:
    paths-ignore:
      - ".vscode/**"
      - "LICENSE"
  pull_request:

jobs:
  skip-duplicate-actions:
    name: Skip duplicate actions
    runs-on: ubuntu-20.04
    outputs:
      should-skip: ${{ steps.skip-check.outputs.should_skip }}

    steps:
      - id: skip-check
        name: Check if workflow is not already running
        uses: fkirc/skip-duplicate-actions@v3.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          concurrent_skipping: "same_content"
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  tests:
    name: Tests
    needs: skip-duplicate-actions
    if: ${{ needs.skip-duplicate-actions.outputs.should-skip != 'true' }}
    runs-on: ubuntu-20.04
    env:
      IMAGE_TARGET: base
      IMAGE_TAG: aifrak/shell-utils:latest
      CACHE_OLD: /tmp/.buildx-cache
      CACHE_NEW: /tmp/.buildx-cache-new

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build image and cache
        uses: docker/build-push-action@v2.5.0
        with:
          load: true
          target: ${{ env.IMAGE_TARGET }}
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=local,src=${{ env.CACHE_OLD }}
          cache-to: type=local,dest=${{ env.CACHE_NEW }}

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf ${{ env.CACHE_OLD }}
          mv ${{ env.CACHE_NEW }} ${{ env.CACHE_OLD }}

      - name: Test
        run: ./run ci:test

      - name: Lint
        run: ./run ci:lint
