name: Tests

on:
  push:
    paths-ignore:
      - '.vscode/**'
      - '**.md'
      - 'LICENSE'
  pull_request:

jobs:
  tests:

    name: Run Shell unit tests
    # Avoid duplicated trigger on "push" and "pull request"
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-20.04

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Shell unit tests
        run: make shell-lint-tests shell-test
