name: Tests

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit tests
        run: make shell-tests-format shell-tests
